## lab 9 : numpy

In [1]:
import numpy as np

In [ ]:
#scalars, vectors, matrices, and tensors
#a = np.array(15) #scalar, rank 0 tensor
#a=np.array([2,3,4,50]) #vector, rank 1 tensor
a=np.array([[2,3,4,50],[2,3,4,50],[2,3,4,50]]) #matrix, rank 2 tensor
#a=np.array([[2,3,4,50],[2,3,4,50]],[[2,3,4,50][2,3,4,50]]) #3d array,
print(a)
print(type(a))
print(a.ndim) #n dimension
print(a.dtype) #data type

[[ 2  3  4 50]
 [ 2  3  4 50]
 [ 2  3  4 50]]
<class 'numpy.ndarray'>
2
int64


In [9]:
#list vs ndarray
import time
a=list(range(100000))
b=list(range(100000,200000))
start = time.time()
for _ in range(1000):
    c=[ i+j for i, j in zip(a,b)]
end =time.time()
print(c[:10])
print(f"{end - start:.6f} seconds")

[100000, 100002, 100004, 100006, 100008, 100010, 100012, 100014, 100016, 100018]
3.220340 seconds


In [ ]:
na = np.array(a)
nb = np.array(b)
start = time.time()
for _ in range(1000):
    nc = na + nb
end =time.time()
print(c[:10])
print(f"{end - start:.6f} seconds")
#병렬로 처리해서 빠름
# GPU로 한번에 여러 element 연산.
# GPU는 내부에 코어가 수만개씩 들어있다. -> 한번에 수만개씩 연산.
# CPU로만 계산해도 병렬 처리가 가능하다. -> SIMD instruction. 이를 위한 레지스터가 따로 있다.
# 근데 numpy는 GPU쓰는 건 아니고 SIMD를 쓴다.

[100000, 100002, 100004, 100006, 100008, 100010, 100012, 100014, 100016, 100018]
0.064094 seconds


In [ ]:
#a = np.zeros((2,5),dtype=np.int32) #axis 0 axis 1
#a = np.ones((2,5))
#a=np.empty((2,5)) #명시적으로 초기화 안해주는것
a=np.full((2,5), 7, dtype=np.float32)
print(a)
print(a.shape)
print(a.dtype)

[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]]
(2, 5)
float32


In [ ]:
a=np.arange(10, dtype=np.float32)

In [18]:
help(np.arange)

a=np.arange(0, 10, 0.1, dtype=np.float32)
print(a)

Help on built-in function arange in module numpy:

arange(start_or_stop, /, stop=None, step=1, *, dtype=None, device=None, like=None)
    arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

    Return evenly spaced values within a given interval.

    ``arange`` can be called with a varying number of positional arguments:

    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.

    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.

    When using a non-integer step, such as