## lab 9 : numpy

In [1]:
import numpy as np

In [2]:
#scalars, vectors, matrices, and tensors
#a = np.array(15) #scalar, rank 0 tensor
#a=np.array([2,3,4,50]) #vector, rank 1 tensor
a=np.array([[2,3,4,50],[2,3,4,50],[2,3,4,50]]) #matrix, rank 2 tensor
#a=np.array([[2,3,4,50],[2,3,4,50]],[[2,3,4,50][2,3,4,50]]) #3d array,
print(a)
print(type(a))
print(a.ndim) #n dimension
print(a.dtype) #data type

[[ 2  3  4 50]
 [ 2  3  4 50]
 [ 2  3  4 50]]
<class 'numpy.ndarray'>
2
int64


In [3]:
#list vs ndarray
import time
a=list(range(100000))
b=list(range(100000,200000))
start = time.time()
for _ in range(1000):
    c=[ i+j for i, j in zip(a,b)]
end =time.time()
print(c[:10])
print(f"{end - start:.6f} seconds")

[100000, 100002, 100004, 100006, 100008, 100010, 100012, 100014, 100016, 100018]
4.642159 seconds


In [4]:
na = np.array(a)
nb = np.array(b)
start = time.time()
for _ in range(1000):
    nc = na + nb
end =time.time()
print(c[:10])
print(f"{end - start:.6f} seconds")
#병렬로 처리해서 빠름
# GPU로 한번에 여러 element 연산.
# GPU는 내부에 코어가 수만개씩 들어있다. -> 한번에 수만개씩 연산.
# CPU로만 계산해도 병렬 처리가 가능하다. -> SIMD instruction. 이를 위한 레지스터가 따로 있다.
# 근데 numpy는 GPU쓰는 건 아니고 SIMD를 쓴다.

[100000, 100002, 100004, 100006, 100008, 100010, 100012, 100014, 100016, 100018]
0.153017 seconds


In [5]:
#a = np.zeros((2,5),dtype=np.int32) #axis 0 axis 1
#a = np.ones((2,5))
#a=np.empty((2,5)) #명시적으로 초기화 안해주는것
a=np.full((2,5), 7, dtype=np.float32)
print(a)
print(a.shape)
print(a.dtype)

[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]]
(2, 5)
float32


In [6]:
a=np.arange(10, dtype=np.float32)

In [ ]:
#help(np.arange) #start, stop, step
# a=np.arange(0, 10, 0.1, dtype=np.float32)

help(np.linspace) #start stop
a=np.linspace(0,10,20)
print(a)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0, *, device=None)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.

In [23]:
#help(np.random.randint) #low high size
a=np.random.randint(0,10,size=(2,3), dtype=np.int32)
print(a)

#help(np.random.uniform) #float 균등분포
b=np.random.uniform(0,10,size=(2,3))
print(b)

#help(np.random.normal) #가우시안
c=np.random.normal(0,1,size=(10,))#표준 정규분포 (0, 0.1하면 더 뾰족해짐)
print(c)

d=np.random.randn(2,3)
#rand는 균등분포(0~1) 난수, randn은 정규분포(평균 0, 표준편차 1) 난수 생성.
print(d)

[[3 9 8]
 [0 3 0]]
[[3.28333162 6.10002829 1.26846473]
 [3.33680729 2.61668655 5.98698362]]
[-0.19729194  1.80118468 -0.08519343  0.36212949  0.60652899  1.39890432
 -1.06560033  0.66957089 -0.56645196  0.96180386]
[[ 0.1629578  -1.25458947  0.55729203]
 [-0.61558438 -0.6097069  -0.02124726]]


In [ ]:
#랜덤이 랜덤이아님
np.random.seed(1)
a=np.random.randn(2,3)
print(a)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]]


In [ ]:
#indexing
a=np.arange(20)
print(a)
print(a[3])
print(a[:7]) #slicing

b=a[:5]#.copy를 해줘야함
b[0]=100 #파이썬에서 슬라이싱하게되면 copy됨 / 넘파이는 안됨
#view를 만들어줌


#fancy indexing
a=np.random.randint(0,10,size=(10,)) #리스트를 갔다가 인덱스로 넘겨줄수잇
print(a)

b=a[[0,5,7,9]]
print(b)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
3
[0 1 2 3 4 5 6]
[0 6 9 9 7 6 9 1 0 1]
[0 6 1 1]


In [ ]:
#boolean indexing
a=np.random.uniform(-1,1, size=(10,))
print(a)

b=a<0 #boolean indexing용 마스크
print(b)

print(a[a<0])

a[a<0] = 0
print(a)

#boolean, fancy indexing만 카피를함

[-0.82991158 -0.92189043 -0.66033916  0.75628501 -0.80330633 -0.15778475
  0.91577906  0.06633057  0.38375423 -0.36896874]
[ True  True  True False  True  True False False False  True]
[-0.82991158 -0.92189043 -0.66033916 -0.80330633 -0.15778475 -0.36896874]
[0.         0.         0.         0.75628501 0.         0.
 0.91577906 0.06633057 0.38375423 0.        ]


In [ ]:
#operation
a=np.random.randint(1,10,(5,))
b=np.random.randint(1,10,(5,))
print(a)
print(b)
print(a+b)
print(a*b) #element wise multiplicaton
print(a/b)
print(a//b) #integer division
print(a%b) #modular
print(a**2)

In [ ]:
#openations: broadcasting
a=np.arrange(10)
print(a)
b=a+10
print(b)

In [32]:
#operation
a= np.arange(1,11)
print(a)
print(np.sin(a)) #라디안값
print(np.cos(a))
print(np.log10(a)) #log 0 == -무한대
#아무것도 안쓰면 ln이고 밑을 써주면 log n이되

[ 1  2  3  4  5  6  7  8  9 10]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251 1.        ]


In [36]:
#operations
a=np.random.randint(0,100,size=(10,))
print(a)
print(np.max(a)) #function call이라는 넘파이함수불러쓰는 형태
print(np.min(a))
print(np.mean(a))
print(np.argmax(a))
print(np.argmin(a))

#obj method style
print(a.max())
print(a.min())


[87 25 71 92 74 62 46 32 88 23]
92
23
60.0
3
9
92
23


In [38]:
#dot product
a=np.array([1,2,3])
b=np.array([3,0,1])
print(a*b) #element wise
print(np.dot(a,b)) #dot product 내적
print(a.dot(b))
print(a@b)

[3 0 3]
6
6
6
