## lab 9 : numpy

In [1]:
import numpy as np

In [2]:
#scalars, vectors, matrices, and tensors
#a = np.array(15) #scalar, rank 0 tensor
#a=np.array([2,3,4,50]) #vector, rank 1 tensor
a=np.array([[2,3,4,50],[2,3,4,50],[2,3,4,50]]) #matrix, rank 2 tensor
#a=np.array([[2,3,4,50],[2,3,4,50]],[[2,3,4,50][2,3,4,50]]) #3d array,
print(a)
print(type(a))
print(a.ndim) #n dimension
print(a.dtype) #data type

[[ 2  3  4 50]
 [ 2  3  4 50]
 [ 2  3  4 50]]
<class 'numpy.ndarray'>
2
int64


In [3]:
#list vs ndarray
import time
a=list(range(100000))
b=list(range(100000,200000))
start = time.time()
for _ in range(1000):
    c=[ i+j for i, j in zip(a,b)]
end =time.time()
print(c[:10])
print(f"{end - start:.6f} seconds")

[100000, 100002, 100004, 100006, 100008, 100010, 100012, 100014, 100016, 100018]
11.847924 seconds


In [4]:
na = np.array(a)
nb = np.array(b)
start = time.time()
for _ in range(1000):
    nc = na + nb
end =time.time()
print(c[:10])
print(f"{end - start:.6f} seconds")
#병렬로 처리해서 빠름
# GPU로 한번에 여러 element 연산.
# GPU는 내부에 코어가 수만개씩 들어있다. -> 한번에 수만개씩 연산.
# CPU로만 계산해도 병렬 처리가 가능하다. -> SIMD instruction. 이를 위한 레지스터가 따로 있다.
# 근데 numpy는 GPU쓰는 건 아니고 SIMD를 쓴다.

[100000, 100002, 100004, 100006, 100008, 100010, 100012, 100014, 100016, 100018]
0.171146 seconds


In [5]:
#a = np.zeros((2,5),dtype=np.int32) #axis 0 axis 1
#a = np.ones((2,5))
#a=np.empty((2,5)) #명시적으로 초기화 안해주는것
a=np.full((2,5), 7, dtype=np.float32)
print(a)
print(a.shape)
print(a.dtype)

[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]]
(2, 5)
float32


In [6]:
a=np.arange(10, dtype=np.float32)

In [7]:
#help(np.arange) #start, stop, step
# a=np.arange(0, 10, 0.1, dtype=np.float32)

help(np.linspace) #start stop
a=np.linspace(0,10,20)
print(a)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0, *, device=None)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.

In [8]:
#help(np.random.randint) #low high size
a=np.random.randint(0,10,size=(2,3), dtype=np.int32)
print(a)

#help(np.random.uniform) #float 균등분포
b=np.random.uniform(0,10,size=(2,3))
print(b)

#help(np.random.normal) #가우시안
c=np.random.normal(0,1,size=(10,))#표준 정규분포 (0, 0.1하면 더 뾰족해짐)
print(c)

d=np.random.randn(2,3)
#rand는 균등분포(0~1) 난수, randn은 정규분포(평균 0, 표준편차 1) 난수 생성.
print(d)

[[1 3 5]
 [2 9 5]]
[[5.85260565 0.23461694 8.36071239]
 [8.50295444 0.33922677 7.55176062]]
[ 0.65222104 -0.54206631  0.78573576 -0.3926128   0.20218866  0.65309657
 -0.70500893  0.7247286  -0.93843334  1.21096333]
[[-1.00172292 -0.82121337  0.18111587]
 [ 0.32465386  0.87082496 -0.78307022]]


In [9]:
#랜덤이 랜덤이아님
np.random.seed(1)
a=np.random.randn(2,3)
print(a)

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]]


In [10]:
#indexing
a=np.arange(20)
print(a)
print(a[3])
print(a[:7]) #slicing

b=a[:5]#.copy를 해줘야함
b[0]=100 #파이썬에서 슬라이싱하게되면 copy됨 / 넘파이는 안됨
#view를 만들어줌


#fancy indexing
a=np.random.randint(0,10,size=(10,)) #리스트를 갔다가 인덱스로 넘겨줄수잇
print(a)

b=a[[0,5,7,9]]
print(b)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
3
[0 1 2 3 4 5 6]
[5 2 4 2 4 7 7 9 1 7]
[5 7 9 7]
[5 2 4 2 4 7 7 9 1 7]


In [11]:
#boolean indexing
a=np.random.uniform(-1,1, size=(10,))
print(a)

b=a<0 #boolean indexing용 마스크
print(b)

print(a[a<0])

a[a<0] = 0
print(a)

#boolean, fancy indexing만 카피를함

[ 0.87825558  0.55677847  0.43194103  0.60551501 -0.81439838  0.0363051
  0.7300405   0.65829381  0.65920672 -0.45390005]
[False False False False  True False False False False  True]
[-0.81439838 -0.45390005]
[0.87825558 0.55677847 0.43194103 0.60551501 0.         0.0363051
 0.7300405  0.65829381 0.65920672 0.        ]


In [12]:
#operation
a=np.random.randint(1,10,(5,))
b=np.random.randint(1,10,(5,))
print(a)
print(b)
print(a+b)
print(a*b) #element wise multiplicaton
print(a/b)
print(a//b) #integer division
print(a%b) #modular
print(a**2)

[9 8 4 7 6]
[2 4 5 9 2]
[11 12  9 16  8]
[18 32 20 63 12]
[4.5        2.         0.8        0.77777778 3.        ]
[4 2 0 0 3]
[1 0 4 7 0]
[81 64 16 49 36]


In [13]:
#openations: broadcasting
a=np.arrange(10)
print(a)
b=a+10
print(b)

AttributeError: module 'numpy' has no attribute 'arrange'

In [ ]:
#operation
a= np.arange(1,11)
print(a)
print(np.sin(a)) #라디안값
print(np.cos(a))
print(np.log10(a)) #log 0 == -무한대
#아무것도 안쓰면 ln이고 밑을 써주면 log n이되

[ 1  2  3  4  5  6  7  8  9 10]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251 1.        ]


In [ ]:
#operations
a=np.random.randint(0,100,size=(10,))
print(a)
print(np.max(a)) #function call이라는 넘파이함수불러쓰는 형태
print(np.min(a))
print(np.mean(a))
print(np.argmax(a))
print(np.argmin(a))

#obj method style
print(a.max())
print(a.min())


[87 25 71 92 74 62 46 32 88 23]
92
23
60.0
3
9
92
23


In [ ]:
#dot product
a=np.array([1,2,3])
b=np.array([3,0,1])
print(a*b) #element wise
print(np.dot(a,b)) #dot product 내적
print(a.dot(b))
print(a@b)

[3 0 3]
6
6
6


In [18]:
#compare np.dot vs list
a=list(range(100000))
b=list(range(100000))

na=np.array(a)
nb=np.array(b)

In [ ]:
%%timeit
 
np.dot(na,nb) #벡터연산을 함

142 μs ± 5.29 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
%%timeit

r2 = sum([i*j for (i, j) in zip(a,b)])

19.6 ms ± 1.09 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [23]:
def softmax(z):
    return np.exp(z) / np.sum(np.exp(z))


z = np.array([1.0, 2.0, 3.0])
print(softmax(z))

[0.09003057 0.24472847 0.66524096]


## 2D matrices, 3D arrays

In [24]:
a=np.random.randint(0, 20, size=(3,4))
print(a)
print(a.shape)
print(a.ndim)

[[11 12 16 13]
 [19  9 18 15]
 [ 0  4 15  2]]
(3, 4)
2


In [ ]:
#indexing
a=np.random.randint(0,20,size=(4,5))
print(a)
print(a[2,3])

b=a[:3,:3]
print(b) 
print()
b=a[::2,::2]
print(b) 

b[0,0]=100
print(a)#numpy는 copy아니고 view

c=a[:, [0,-1]]
print(c)

c[0,0]=1000 #c는 copy를 해온거라서 원본인 a는 바뀌지 않는다
print(a)

[[16  0 18 10  8]
 [13  3  0  8 13]
 [18 15  9  0 12]
 [19 17 10 12 15]]
0
[[16  0 18]
 [13  3  0]
 [18 15  9]]

[[16 18  8]
 [18  9 12]]
[[100   0  18  10   8]
 [ 13   3   0   8  13]
 [ 18  15   9   0  12]
 [ 19  17  10  12  15]]
[[100   8]
 [ 13  13]
 [ 18  12]
 [ 19  15]]
[[100   0  18  10   8]
 [ 13   3   0   8  13]
 [ 18  15   9   0  12]
 [ 19  17  10  12  15]]


In [ ]:
a = np.arange(20)
print(a)
print(a.shape)
b=a.reshape(4, -1)
print(b) #reshape해도 원본수정됨
b[1,1]=1000
print(a)
#strid 얼마만큼 가면 줄을 바꿀 것인지 (row를 바꿀것인지)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[   0    1    2    3    4    5 1000    7    8    9   10   11   12   13
   14   15   16   17   18   19]


In [39]:
a=np.arange(10)
print(a)
print(a.shape)
b=a[:,None]
print(b)
print(b.shape)

b=a[None,:]
print(b)
print(b.shape)

b=a[np.newaxis,:,np.newaxis]
print(b)
print(b.shape)


[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)
[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)
[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]
  [9]]]
(1, 10, 1)


In [ ]:
#c=b.reshape((10,))
c=b.reshape(-1) #view
print(c)
print(c.shape) 

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [43]:
c=b.flatten()#copy
print(c)
print(c.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [46]:
#transpose
a=np.arange(10).reshape((5,-1))
print(a.T)
print(a.T.shape)

[[0 2 4 6 8]
 [1 3 5 7 9]]
(2, 5)


In [53]:
#broadcasting
a=np.arange(12).reshape((3,-1))
print(a)
print(a*10)

#b=np.array([1,0,-1,0])
b=np.array([1,0,-1]).reshape(3,1)
print(b)
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]
[[ 1]
 [ 0]
 [-1]]
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [63]:
#통계함수들
#sum(), min(), mean(), max(), argmin(), argmax()
np.random.seed(1)
a=np.random.randint(0,20,size=(4,5))
print(a)
print()
print(a.sum(axis=0, keepdims=True))
print()
print(b.shape)

[[ 5 11 12  8  9]
 [11  5 15  0 16]
 [ 1 12  7 13  6]
 [18  5 18 11 10]]

[[35 33 52 32 41]]

(3, 1)


In [69]:
#sorting
a=np.random.randint(1,20,size=(4,5))
print(a)
print()

a.sort(axis=1) #inplace sorting a값 자체가 바뀜
print(a)
print()

b=np.sort(a, axis=0) #a는 안바뀜
print(a)
print(b)

[[11 18  8 11  1]
 [13  2 10 19  2]
 [ 3 13  8  3 11]
 [ 1 10 19  7  3]]

[[ 1  8 11 11 18]
 [ 2  2 10 13 19]
 [ 3  3  8 11 13]
 [ 1  3  7 10 19]]

[[ 1  8 11 11 18]
 [ 2  2 10 13 19]
 [ 3  3  8 11 13]
 [ 1  3  7 10 19]]
[[ 1  2  7 10 13]
 [ 1  3  8 11 18]
 [ 2  3 10 11 19]
 [ 3  8 11 13 19]]
