In [ ]:
##OOP
#isinstance(,)
#class a:
    #def __init__(,,)
    #def norm(self):
    #def distance(self, another point)
#extend, append

## NUMPY
#randint, uniform, normal, randn , seed / arange / array, dtype, shape, ndim / linspace / zero, ones, empty, full
#slicing :: (파이썬은 copy, numpy view, fancyindexing : copy) / masking
#reshape (view) -1, .T(view), flatten(copy), astype

#a[a<0] 를 "읽기" 하면 copy 반환, a[a<0] = 값 은 원본 위치에 직접 쓰기
# * @ / //
#np.dot np.pi
#max, min, mean, argmax, argmin, maximum, minimum, sum
#sin cos는 라디안값을 반환함 , log, exp
#NumPy shape는 tuple로 저장
#None (= np.newaxis) copy

#sum, mean, std(표편), var(분산), max, min, prod(곱) abs() 절댓값 nan(not a num)
#cumsum(), cumprod()(누적곱),

########np.vstack hstack, tile, repeat




## MATPOLTLIB
#open -> np array 로 저장 ->save
#plt.imshow
#fromarray(slicing한 배열)

# fig,ax=plt.subplots(1,2,figsize=(10,4))
# ax[0].plot(X,Y,label = r'sigmoid(x)')
# ax[0].set(xlabel = "x", ylabel = "y")
# ax.set_title("Age Distribution")
# ax[0].set_yticks(np.linspace(0,1,11))
# ax[0].grid(axis = 'both')
# ax[0].legend(loc='upper right')
# plt.show()

#ax[0].scatter(X,Y, edgecolor ='k', color='r')
#ax[1].hist(X, np.arange(-3,3,0.2), edgecolor='k') #bins=20 값들을 몇 개 구간으로 나눌지

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

def mean_2d(X, stride=2):
    h, w = X.shape
    
    out_h = h // stride
    out_w = w // stride
    
    result = np.zeros((out_h, out_w))
    
    for i in range(out_h):
        for j in range(out_w):
            block = X[
                i*stride:(i+1)*stride,
                j*stride:(j+1)*stride
            ]
            
            result[i, j] = np.mean(block)
    
    return result

    
X=np.arange(16).reshape((4,4))
print(f"X:\n{X}")
print(f"X:\n{mean_2d(X,stride=2)}")

X:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
X:
[[ 2.5  4.5]
 [10.5 12.5]]


In [ ]:
X=np.linspace(-3,3,10) #미친년아
X

array([-3.        , -2.33333333, -1.66666667, -1.        , -0.33333333,
        0.33333333,  1.        ,  1.66666667,  2.33333333,  3.        ])

In [4]:
import numpy as np

def my_tri(n=3):
    A = np.zeros((n, n), dtype=bool)
    
    for i in range(n):
        A[i, :i+1] = True
    
    return A

print(my_tri(5))

[[ True False False False False]
 [ True  True False False False]
 [ True  True  True False False]
 [ True  True  True  True False]
 [ True  True  True  True  True]]


In [ ]:
class Time:
    def __init__(self, hour, minute):
        self.minute = hour * 60 + minute

    def __str__(self):
        h = self.minute // 60
        m = self.minute % 60
        return f"{h} hours and {m} minutes"

    def __add__(self, other):
        total = self.minute + other.minute
        
        h = total // 60
        m = total % 60
        
        return Time(h, m)

    def __lt__(self, other):
        return self.minute < other.minute


t1 = Time(2, 10)
t2 = Time(1, 50)

print(t1 + t2)  
print(t1 < t2)      

4 hours and 0 minutes
False
