## week 08

In [2]:
import numpy as np

In [55]:
#1
a=np.arange(0,26,1).reshape((2,-1))
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24 25]]


In [59]:
#2
print(a.T) #전치 : 행과 열을 바꿈
print(a.reshape((13,2))) #단순 모양 바꿈

[[ 0 13]
 [ 1 14]
 [ 2 15]
 [ 3 16]
 [ 4 17]
 [ 5 18]
 [ 6 19]
 [ 7 20]
 [ 8 21]
 [ 9 22]
 [10 23]
 [11 24]
 [12 25]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]]


In [5]:
#3
a=np.arange(0,27).reshape(3,3,3)
a[:,1,1]=999
a

array([[[  0,   1,   2],
        [  3, 999,   5],
        [  6,   7,   8]],

       [[  9,  10,  11],
        [ 12, 999,  14],
        [ 15,  16,  17]],

       [[ 18,  19,  20],
        [ 21, 999,  23],
        [ 24,  25,  26]]])

In [6]:
#4
a=np.zeros((4,4))+10
print(a)
b=np.ones((4,4))*10
print(b)
c=np.full((4,4), 10, dtype=np.float32)
print(c)

[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]


In [7]:
#5
a = np.vstack((np.arange(20).reshape(5,4), np.full((5,4), -999)))
# 세로 방향으로 붙이기
print(a)

[[   0    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]
 [  12   13   14   15]
 [  16   17   18   19]
 [-999 -999 -999 -999]
 [-999 -999 -999 -999]
 [-999 -999 -999 -999]
 [-999 -999 -999 -999]
 [-999 -999 -999 -999]]


In [8]:
#6
a = np.hstack((np.arange(20).reshape(5,4), np.full((5,4), -999)))
# 가로 방향으로 붙이기
print(a)

[[   0    1    2    3 -999 -999 -999 -999]
 [   4    5    6    7 -999 -999 -999 -999]
 [   8    9   10   11 -999 -999 -999 -999]
 [  12   13   14   15 -999 -999 -999 -999]
 [  16   17   18   19 -999 -999 -999 -999]]


In [9]:
#7
from math import exp
data=[1,2,4,8]
print(np.exp(data))
#exp(data) #이 함수는 한 번에 하나의 숫자(스칼라)만 처리
for i in data:
    print(exp(i))

[2.71828183e+00 7.38905610e+00 5.45981500e+01 2.98095799e+03]
2.718281828459045
7.38905609893065
54.598150033144236
2980.9579870417283


In [17]:
#8
a=np.random.rand(4,)
b=np.random.randn(4,3)
c=np.full((1,4), 4, dtype=np.float32)
print(a)
print(b)
print(c)

[0.91777412 0.71457578 0.54254437 0.14217005]
[[ 1.484537   -1.07980489 -1.97772828]
 [-1.7433723   0.26607016  2.38496733]
 [ 1.12369125  1.67262221  0.09914922]
 [ 1.39799638 -0.27124799  0.61320418]]
[[4. 4. 4. 4.]]


In [21]:
#9
print(a.shape)
print(b.shape)
print(c.shape)
# a는 1차원 배열이지만, reshape 등을 이용하면 b와 연산 가능하다

print(b*a.reshape(4,1))
# c.T는 b와 원소곱을 하면 broadcasting에 의해 각 행마다 같은 값이 곱해진다
print(b*c.T)

(4,)
(4, 3)
(1, 4)
[[ 1.36246964 -0.99101698 -1.81510784]
 [-1.24577162  0.1901273   1.7042399 ]
 [ 0.60965236  0.90747176  0.05379285]
 [ 0.19875321 -0.03856334  0.08717927]]
[[ 5.93814801 -4.31921954 -7.91091312]
 [-6.97348918  1.06428066  9.53986932]
 [ 4.49476501  6.69048885  0.39659686]
 [ 5.59198551 -1.08499195  2.45281674]]


In [27]:
#10
print(f"b+a = {b.T+a}") #b.T(3,4)
print(f"b+c = {b.T+c}")

b+a = [[ 2.40231112 -1.02879651  1.66623562  1.54016642]
 [-0.16203076  0.98064595  2.21516658 -0.12907794]
 [-1.05995416  3.09954311  0.64169358  0.75537423]]
b+c = [[5.484537   2.2566277  5.12369125 5.39799638]
 [2.92019511 4.26607016 5.67262221 3.72875201]
 [2.02227172 6.38496733 4.09914922 4.61320418]]


In [12]:
#11
a=np.linspace(0,1,11)
print(f"using linspace :{a}")
a = np.arange(0, 1.1, 0.1)
print(f"using arange :{a}")

using linspace :[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
using arange :[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [13]:
#12
matrix = np.ones((5,5)) * np.arange(-2, 3)
matrix

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

In [33]:
#13
np.random.seed(10)
a=np.random.randint(-5,6,size=(5,5))
#rng=np.random.default_rng(10)
#a=rng.integers(-5,6,size=(5,5))
matrix-=a
print(matrix)

[[-6.  0.  5.  5. -2.]
 [ 3.  3. -5. -2. -2.]
 [ 3. -6. -3.  0.  3.]
 [ 0.  4.  1.  0. -1.]
 [-7.  3. -3.  2.  6.]]


In [41]:
#14
matrix[matrix<0]=0
matrix
print(np.maximum(0,matrix))

[[0. 0. 5. 5. 0.]
 [3. 3. 0. 0. 0.]
 [3. 0. 0. 0. 3.]
 [0. 4. 1. 0. 0.]
 [0. 3. 0. 2. 6.]]


In [71]:
#15
p=np.tile(np.arange(1,6).reshape((1,5)),(2,2))
print(p)

[[1 2 3 4 5 1 2 3 4 5]
 [1 2 3 4 5 1 2 3 4 5]]


In [70]:
#16
p = np.repeat(np.arange(1,7).reshape((1,2,-1)), 2 ,axis=0)
print(p)
p = np.repeat(np.arange(1,7).reshape((1,2,-1)), 3, axis=1)
print(p)
p = np.repeat(np.arange(1,7).reshape((1,2,-1)),4, axis=2)
print(p)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]
  [4 5 6]
  [4 5 6]
  [4 5 6]]]
[[[1 1 1 1 2 2 2 2 3 3 3 3]
  [4 4 4 4 5 5 5 5 6 6 6 6]]]


In [79]:
#17
array=[84, 91, 13, 65, 8, 31, 48, 4]
print(f'max value index : {np.argmax(array)}')
print(f'min value index : {np.argmin(array)}')

max value index : 1
min value index : 7


In [94]:
#18
a=np.random.randint(-100, 101,size=10000000)
print(f'mix value : {np.min(a)}')
print(f'max value : {np.max(a)}')
print(f'mean value : {np.mean(a)}')
print(f'standard deviation value : {np.std(a)}')

mix value : -100
max value : 100
mean value : 0.016239
standard deviation value : 58.022059552336465


In [ ]:
#19
a=np.random.normal(5, 2, size=10000000)
print(f'mix value : {np.min(a)}')
print(f'max value : {np.max(a)}')
print(f'mean value : {np.mean(a)}')
print(f'standard deviation value : {np.std(a)}')

mix value : -5.964063852610684
max value : 15.299258846594379
mean value : 5.000302885214222
standard deviation value : 2.0007412213203364


In [118]:
#20
a = np.array([[4,1],[2,4]])
b = np.array([[5,6],[1,8]])

print((a @ b) @ (b @ a))

[[1312 1665]
 [1328 1858]]


In [ ]:
#21
c=np.array([[ 1, 2],[8, 4],[3, 9]])
print((c@a)+(c@b))
#행렬곱을 할 때 a@b라면 a의 열과 b의 행의 크기가 같아야한다.

[[ 15  31]
 [ 84 104]
 [ 54 129]]


In [ ]:
#22
k=np.ones((3,4))*np.linspace(-1,2.5,4)
print(k) 
print(f'높임 : {np.ceil(k)}')   
print(f'내림 : {np.floor(k)}')  
print(f'반올림 : {np.round(k)}')  


[[-1.          0.16666667  1.33333333  2.5       ]
 [-1.          0.16666667  1.33333333  2.5       ]
 [-1.          0.16666667  1.33333333  2.5       ]]
높임 : [[-1.  1.  2.  3.]
 [-1.  1.  2.  3.]
 [-1.  1.  2.  3.]]
내림 : [[-1.  0.  1.  2.]
 [-1.  0.  1.  2.]
 [-1.  0.  1.  2.]]
반올림 : [[-1.  0.  1.  2.]
 [-1.  0.  1.  2.]
 [-1.  0.  1.  2.]]


In [129]:
#23
print(np.sum(k)) #원소의 총합
print(np.cumsum(k)) #원소의 누적되는 합을 순차적으로 구해주는거 같은데요

9.0
[-1.         -0.83333333  0.5         3.          2.          2.16666667
  3.5         6.          5.          5.16666667  6.5         9.        ]


In [ ]:
#24
random_value = np.array([13, 20, 28, 38, 14, 41, 0, 37])
print(random_value[ : , np.newaxis])

[[13]
 [20]
 [28]
 [38]
 [14]
 [41]
 [ 0]
 [37]]


In [140]:
#25
print(np.sort(random_value)[:,np.newaxis])

print(random_value[np.argsort(random_value)][:,np.newaxis])

[[ 0]
 [13]
 [14]
 [20]
 [28]
 [37]
 [38]
 [41]]
[[ 0]
 [13]
 [14]
 [20]
 [28]
 [37]
 [38]
 [41]]


In [12]:
import numpy as np
def tri_i(n=5):
    X=np.arange(0,n*n).reshape(n,n)
    a=np.arange(0,n)
    b=np.arange(0,a)
    X=True
    X[b:a]=False
    return X

#tri_i(4)

def my(x, size):
    return np.mean(x[::size, ::size])

x=np.arange(1,17).reshape(4,4)
print(my(x,2))

np.full((2,3,4), 5, dtype=np.float32)

6.0


array([[[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]]], dtype=float32)